#!/bin/sh

npm ls ts-node --depth 1 2>&1 1>/dev/null;

if [ $? -gt 0 ]; then
  npm exec node-pg-migrate -- "$@";
else
  npm exec ts-node -- -r tsconfig-paths/register ./node_modules/.bin/node-pg-migrate "$@";
fi;
